/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IAlchemistNFTEvents,
  IAlchemistNFTEventsInterface,
} from "../IAlchemistNFTEvents";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "Alchemist",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "NFTWrapper",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "Jpeg",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "Curve",
        type: "address",
      },
    ],
    name: "Initialized",
    type: "event",
  },
];

export class IAlchemistNFTEvents__factory {
  static readonly abi = _abi;
  static createInterface(): IAlchemistNFTEventsInterface {
    return new utils.Interface(_abi) as IAlchemistNFTEventsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAlchemistNFTEvents {
    return new Contract(address, _abi, signerOrProvider) as IAlchemistNFTEvents;
  }
}
