/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IJpeg, IJpegInterface } from "../IJpeg";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_nftIndex",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "_useInsurance",
        type: "bool",
      },
    ],
    name: "borrow",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_nftIndex",
        type: "uint256",
      },
    ],
    name: "closePosition",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_nftIndex",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "repay",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IJpeg__factory {
  static readonly abi = _abi;
  static createInterface(): IJpegInterface {
    return new utils.Interface(_abi) as IJpegInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IJpeg {
    return new Contract(address, _abi, signerOrProvider) as IJpeg;
  }
}
