/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { INFTWrapper, INFTWrapperInterface } from "../INFTWrapper";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "safeTransferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        internalType: "bool",
        name: "approved",
        type: "bool",
      },
    ],
    name: "setApprovalForAll",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class INFTWrapper__factory {
  static readonly abi = _abi;
  static createInterface(): INFTWrapperInterface {
    return new utils.Interface(_abi) as INFTWrapperInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): INFTWrapper {
    return new Contract(address, _abi, signerOrProvider) as INFTWrapper;
  }
}
